
@id= sb-hanacap!t114777
@secret= xxx

@username=koray.yersel@q-perior.com
@password=xxx

###
# @name tokenRequest
POST https://828494c6trial.authentication.eu10.hana.ondemand.com/oauth/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Basic {{id}}:{{secret}}

grant_type=password&username={{username}}&password={{password}}&response_type=token

###

GET https://828494c6trial-dev-hanacap-srv.cfapps.eu10.hana.ondemand.com/catalog/Interactions_Header
Authorization: Bearer {{tokenRequest.response.body.access_token}}
####
